services:
  - type: web
    name: phishguard
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m app.train_model
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
